export const StudyTestTypes = Object.freeze({
  FIRST_TYPE: "TYPES/FIRST_TYPE",
  SECOND_TYPE: "TYPES/SECOND_TYPE",
  THIRD_TYPE: "TYPES/THIRD_TYPE",
  FOURTH_TYPE: "TYPES/FOURTH_TYPE",
  FIFTH_TYPE: "TYPES/FIFTH_TYPE",
});
